# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  #
  # This workflow contains a job called build
  #
  # Build first
  build:
    #
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    #
    # Runs a single command using the runners shell
    - name: Install requirements
      run: |
        sudo apt-get update; sudo apt-get install -y gfortran openmpi-bin libopenmpi-dev
    #
    # Runs a set of commands using the runners shell
    - name: Compile
      run: make -j
    #
    # Runs a set of commands using the runners shell
    - name: Chdir
      run: ln -s xcompact3d examples/Taylor-Green-Vortex/xcompact3d; cd examples/Taylor-Green-Vortex/
    #
    # Run 2D case, periodic, 1 time step
    - name: ncl00
      run: echo "ncl00" > ~/log_tgv2d.txt; ./xcompact3d 2D-ncl00.i3d; mpirun -np 1 ./xcompact3d 2D-ncl00.i3d > log; tail -n40 log >> ~/log_tgv2d.txt
    #
    # Run 2D case, symmetry, 1 time step
    - name: ncl11
      run: echo "ncl11" >> ~/log_tgv2d.txt; mpirun -np 1 ./xcompact3d 2D-ncl11.i3d > log; tail -n40 log >> ~/log_tgv2d.txt
    #
    # Run 2D case, periodic, time-implicit Y diffusion, 1 time step
    - name: ncl00_imp
      run: echo "ncl00_imp" >> ~/log_tgv2d.txt; mpirun -np 1 ./xcompact3d 2D-ncl00_imp1.i3d > log; tail -n40 log >> ~/log_tgv2d.txt
    #
    # Run 2D case, symmetry, time-implicit Y diffusion, 1 time step
    - name: ncl11_imp
      run: echo "ncl11_imp" >> ~/log_tgv2d.txt; mpirun -np 1 ./xcompact3d 2D-ncl11_imp2.i3d > log; tail -n40 log >> ~/log_tgv2d.txt
    #
    # Keep the log
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ~/log_tgv2d.txt

